---
name: "trigger"

databases:
  - name: main
    postgres:
      runOutbox: true
      outboxDelayable: true
      dbName: trigger
      serverGroup: default
      dbExtensions:
        - "uuid-ossp"

      migrateContainer:
        image:
          name: trigger
        command: [migrate]
        envVars:
          - name: "POSTGRES_URL"
            database:
              databaseName: main

targets:
  - name: "/o5.trigger.v1.topic.TickTopic"
  - name: "/o5.trigger.v1.topic.TriggerTopic"

runtimes:
  - name: main
    subscriptions:
      - name: "/o5.trigger.v1.topic.TriggerTopic"
    routes:
      - prefix: "/trigger/v1/"
        protocol: ROUTE_PROTOCOL_HTTP

    containers:
      - name: main
        demand: DEMAND_LIGHT
        image:
          name: trigger
        command: [serve]
        envVars:
          - name: "POSTGRES_URL"
            database:
              databaseName: main
          - name: PUBLIC_ADDR
            value: ":8080"
